services:
  redis:
    image: "redis:alpine"
  celery-worker:
    image: inoki-giskard-backend
    command: ./run-celery.sh
  backend:
    build: .
    image: inoki-giskard-backend
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    depends_on:
      - redis
      - celery-worker
