#!/usr/bin/env python

import sys
import json
import os

import millennium_falcon.odds

def print_help():
    print("Usage:                                                           ")
    print("    ./give-me-the-odds <millennium-falcon.json> <empire.json>    ")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print_help()
        exit(1)

    # Call the core module to calculate the odds
    try:
        with open(sys.argv[1], "r") as falcon_status_fd:
            with open(sys.argv[2], "r") as empire_plan_fd:
                error_code, odds = millennium_falcon.\
                    odds.calculate(json.load(falcon_status_fd), json.load(empire_plan_fd), \
                        base_dir=os.path.dirname(sys.argv[1]))
                if error_code != 0:
                    print("Error:", error_code)
                    exit(1)
                print(int(odds))
    except Exception as e:
        print("Exception:", e)
        exit(1)
