#!/usr/bin/env python

import sys
import json

def print_help():
    pass

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print_help()
        exit(1)

    # TODO: Call the core module to calculate the odds
